CREATE DATABASE P2_WEB2;
USE P2_WEB2;

CREATE USER 'PROVAP2'@'%' IDENTIFIED BY 'SENHA';
GRANT ALL PRIVILEGES ON * . * TO 'PROVAP2'@'%';
FLUSH PRIVILEGES;

CREATE TABLE ALUNO
(
    ID_ALUNO        INT         NOT NULL,
    CPF              INT         NOT NULL,
    NOME             VARCHAR(50) NOT NULL,
    FONE             VARCHAR(30)
);

ALTER TABLE ALUNO ADD CONSTRAINT ALUNO_PK PRIMARY KEY(ID_ALUNO);

CREATE SEQUENCE ALUNO_SEQ
INCREMENT BY 1
NOMINVALUE 
NOMAXVALUE
NOCYCLE 
NOCACHE;