CREATE DATABASE P2_WEB2;
USE P2_WEB2;

CREATE USER 'PROVAP2'@'%' IDENTIFIED BY 'SENHA';
GRANT ALL PRIVILEGES ON * . * TO 'PROVAP2'@'%';
FLUSH PRIVILEGES;

CREATE TABLE ALUNO
(
    ID_ALUNO        INT         NOT NULL,
    CPF             INT,
    NOME            VARCHAR(50),
    FONE            VARCHAR(30),
    EMAIL           VARCHAR(100)
);

ALTER TABLE ALUNO ADD CONSTRAINT ALUNO_PK PRIMARY KEY(ID_ALUNO);

CREATE SEQUENCE ALUNO_SEQ
INCREMENT BY 1
NOMINVALUE 
NOMAXVALUE
NOCYCLE 
NOCACHE;
